name: Fenny79
favicon: null
layout_spectrum: 0.9311379755381495
typography_spectrum: 0.8446941729635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.11162798223085701
  lightness: 0.8320115501992404
  saturation: 0.18050663196481764
  rhythmicContrast: 0.4393408023752272
purpose: []
