name: Fenny79
favicon: null
layout_spectrum: 0.90084
typography_spectrum: 0.06925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.11162798223085701
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
